### ISSUE TITLE
Tattoo not showing, Player Clothing

### ISSUE THREAD

**Issue by OfficialRDB** [MrEvilGamer/qb-tattooshop#10]
- The tattoo is not visible after buying and backing out of the menu.
It does show when you are in the menu, also the tattoo's you bought earlier.

- The player still has his clothing on, so you can't see how it looks.

**Comment by sinfuljosh** [comment]
The clothing is because its configured to use cui-character.

**Comment by OfficialRDB** [comment]
> 
> 
> The clothing is because its configured to use cui-character.

I tought this would do the job right ?

`
function GetNaked()

        if GetEntityModel(PlayerPedId()) == 'mp_m_freemode_01' then
                      local NakedData = {
                outfitData = {
                    ["arms"]= {item = 15,texture=0};
                    ["t-shirt"]   = { item = 15, texture = 0},  -- Nek / Das
                    ["torso2"]= {item = 15,texture=0},
                    ["pants"]= {item = 21,texture=0},
                }
            }
            TriggerEvent('qb-clothing:client:loadOutfit', NakedData)
        else
            local NakedData = {
                outfitData = {
                    ["arms"]= {item = 15,texture=0};
                    ["t-shirt"]   = { item = 15, texture = 0},  -- Nek / Das
                    ["torso2"]= {item = 15,texture=0},
                    ["pants"]= {item = 21,texture=0},
                }
            }
            TriggerEvent('qb-clothing:client:loadOutfit', NakedData)
        end
end
`

**Comment by sinfuljosh** [comment]
Client side script. Line 92, would copy the code but I’m replying from my phone. Hope this helps anyone wanting to know what part of the code needed this change

**Comment by netlork** [comment]
Please, submit this to apply changes to original file :D
