### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [MrEvilGamer/qb-tattooshop#12]
I get this after a fresh install

**[script:qb-tattooshop] Error loading script config.lua in resource qb-tattooshop: @qb-tattooshop/config.lua:24: attempt to call a nil value (global 'GetInteriorAtCoords')
[script:qb-tattooshop] stack traceback:
[script:qb-tattooshop] 	@qb-tattooshop/config.lua:24: in main chunk**

**Comment by josh-tf** [comment]
Change the function at the bottom of the config file to this:

```
if not IsDuplicityVersion() then
	Config.interiorIds = {}
	for k, v in ipairs(Config.Shops) do
		Config.interiorIds[#Config.interiorIds + 1] = GetInteriorAtCoords(v)
	end
end
```

**Comment by ghost** [comment]
> Change the function at the bottom of the config file to this:
> 
> ```
> if not IsDuplicityVersion() then
> 	Config.interiorIds = {}
> 	for k, v in ipairs(Config.Shops) do
> 		Config.interiorIds[#Config.interiorIds + 1] = GetInteriorAtCoords(v)
> 	end
> end
> ```

Thank you sir
