### ISSUE TITLE
refreshskin problem

### ISSUE THREAD

**Issue by kingofkingzcd** [MrEvilGamer/qb-tattooshop#19]
when refreshing skin tattoos dont show back up until you re visit the tattoo shop.

**Comment by MrEvilGamer** [comment]
hey there!
i wanted to tell you that in your reload skin event command 
if it's server sided then you have to add 
TriggerServerEvent('Select:Tattoos')
if it's client sided then you have to add 
TriggerEvent('Select:Tattoos')
or else every time you will refresh your skin it won't pop up
