### ISSUE TITLE
[Suggestion] Menu & Back

### ISSUE THREAD

**Issue by OfficialRDB** [MrEvilGamer/qb-tattooshop#8]
I'm not sure if you are still updating but would be nice to have it converted to the same menu as in QB Framework it self 'MenuV'
Maybe tattoos for the back too

**Comment by MrEvilGamer** [comment]
Should Be Fixed Now

**Comment by OfficialRDB** [comment]
> 
> 
> Should Be Fixed Now

Both of my suggestions ?
-Tattoo's for the back
-MenuV integration

**Comment by MrEvilGamer** [comment]
Thanks for the suggestion will try to look forw
